version: "3"
services:
  pg:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - todo
    environment:
      - POSTGRES_PASSWORD=passwd
  todo:
    image: tomoyat1/yet-another-todo-app:latest
    ports:
      - "8080:8080"
    environment:
      - TODO_DB_USER=postgres
      - TODO_DB_PASSWD=passwd
      - TODO_DB_HOST=pg
      - TODO_DB_PORT=5432
      - TODO_DB_NAME=todo
    networks:
      - todo
    depends_on:
      - pg
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo
    depends_on:
      - todo
volumes:
  postgres-data:
networks:
  todo:
    driver: bridge
