version: "3"
services:
  postgres:
    image: postgres:10.3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - postgres
    environment:
      - POSTGRES_PASSWORD=passwd
volumes:
  postgres-data:
networks:
  postgres:
    driver: bridge
